### ISSUE TITLE
Autenticacao da API com JWT

### ISSUE THREAD

**Issue by eduardomoroni** [project-australia/Sydney#9]
A ideia é simples:
O Firebase vai cuidar da sessao client-side.
Com isso, se o usuario estiver logado ele terá acesso a um token do firebase.

Nosso backend recebera um header contendo um JWT com esse token, [decriptado talvez?],
Ai o nosso back-end vai usar o proprio firebase para validar este token. 
Com isso a gente tem a aplicacao segura.

Any concerns @hebertporto ?

**Comment by eduardomoroni** [comment]
Implementacao easy breeze
https://firebase.google.com/docs/auth/admin/verify-id-tokens

**Comment by hebertporto** [comment]
Pra mim está ótimo ! ! pra cima deles
